#!/usr/bin/env sh
# Copyright 2025 The Wardyn Authors
# SPDX-License-Identifier: Apache-2.0
#
# install.sh — install Wardyn on this machine.
#
#   curl -fsSL https://github.com/cjohnstoniv/wardyn/releases/download/v0.6.6/install.sh | sh
#
# That URL is the cosign-signed release asset, covered by SHA256SUMS. Curling
# this file from `main` also works, but nothing signs tip-of-main. README.md
# carries the same URL; RELEASING.md step 1b sweeps the version in both.
#
# Pulls the published, cosign-signed images (docs/VERIFY.md) and starts the
# containerized control plane. No clone, no build, no toolchain — Docker is the
# only requirement.
#
# Deploying to Kubernetes instead? That path needs no clone either:
#   helm install wardyn oci://ghcr.io/cjohnstoniv/charts/wardyn --version <ver>
#
# Building from source is a CONTRIBUTOR path, not an install path: see
# CONTRIBUTING.md.
#
# Env: WARDYN_VERSION (default: latest release), WARDYN_HOME (default ~/.wardyn),
#      WARDYN_PORT (default 8080), WARDYN_NS (default "wardyn" — the container-name
#      prefix; change it to run a second install alongside the first).
#
# ponytail: sh, not bash — this is the one script that runs on a machine we know
# nothing about, before anything of ours is installed.
set -eu

REPO=cjohnstoniv/wardyn
HOME_DIR="${WARDYN_HOME:-$HOME/.wardyn}"
PORT="${WARDYN_PORT:-8080}"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is required — https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "the docker daemon is not reachable (is Docker running?)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (docker-compose v1 is not supported)"

# Resolve the version. The GitHub API needs no token for a public repo; if it is
# rate-limited or offline, say so rather than silently installing something else.
#
# NOT `releases/latest`: that endpoint EXCLUDES pre-releases, and RELEASING.md
# mandates `--prerelease` on every Wardyn release — so it returns HTTP 404 and
# this script used to die two lines below on every install. `releases?per_page=1`
# is the newest release of any kind. RELEASING.md says the same thing about
# `releases/latest/download/`.
VERSION="${WARDYN_VERSION:-}"
if [ -z "$VERSION" ]; then
  say "Resolving the latest release"
  VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases?per_page=1" 2>/dev/null \
            | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)
  [ -n "$VERSION" ] || die "could not resolve the latest release — set WARDYN_VERSION=vX.Y.Z"
fi
case "$VERSION" in v*) ;; *) VERSION="v$VERSION" ;; esac
SEMVER="${VERSION#v}"
say "Installing Wardyn ${VERSION} into ${HOME_DIR}"

# Container names are ${WARDYN_NS:-wardyn}-*, so a stack already running from a
# clone owns them. Surface that as a sentence instead of a daemon conflict error
# fifty lines into a compose transcript.
NS="${WARDYN_NS:-wardyn}"
if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "${NS}-api"; then
  die "a Wardyn stack named '${NS}' already exists on this Docker daemon.
  Stop it first (cd ${HOME_DIR} && docker compose down), or install alongside it
  under a different name and free ports:
      WARDYN_NS=wardyn2 WARDYN_PORT=8090 WARDYN_PG_PORT=5433 \\
        WARDYN_REGISTRY_PORT=5011 WARDYN_SSH_PORT=2223 WARDYN_UI_SANDBOX_PORT=8091 \\
        curl -fsSL <this-url> | sh"
fi

mkdir -p "$HOME_DIR"
cd "$HOME_DIR"

# The compose file comes from the tag itself, so this works the moment a release
# exists — no dependency on a release asset having been uploaded.
say "Fetching the compose definition"
curl -fsSL "https://raw.githubusercontent.com/${REPO}/${VERSION}/deploy/compose/docker-compose.yaml" \
  -o docker-compose.yaml || die "could not fetch the compose file for ${VERSION}"

if [ ! -f .env ]; then
  say "Minting this install's secret-store key"
  # Same mechanism the repo's own installers use. The key never leaves this box.
  KEY=$(docker run --rm "ghcr.io/${REPO%/*}/wardynd:${SEMVER}" -gen-age-key 2>/dev/null \
        | grep -E '^AGE-SECRET-KEY-' | head -1 || true)
  [ -n "$KEY" ] || die "could not mint an age key from ghcr.io/${REPO%/*}/wardynd:${SEMVER}"
  TOKEN=$(docker run --rm "ghcr.io/${REPO%/*}/wardynd:${SEMVER}" -gen-age-key 2>/dev/null | sha256sum | cut -c1-48)

  cat > .env <<EOF
# Generated by install.sh for Wardyn ${VERSION}. Safe to edit.
WARDYN_AGE_KEY=${KEY}
WARDYN_ADMIN_TOKEN=${TOKEN}
WARDYN_UP_PORT=${PORT}
WARDYN_NS=${NS}
WARDYN_PG_PORT=${WARDYN_PG_PORT:-5432}
WARDYN_REGISTRY_PORT=${WARDYN_REGISTRY_PORT:-5010}
WARDYN_SSH_PORT=${WARDYN_SSH_PORT:-2222}
WARDYN_UI_SANDBOX_PORT=${WARDYN_UI_SANDBOX_PORT:-8081}
# The PORT vars above only publish the host port. The LISTEN vars below are what
# actually start a listener — empty means off, and the host key is not even
# generated. Setting one without the other gives a published port that refuses
# every connection, which is what this installer shipped in 0.6.3.
WARDYN_SSH_LISTEN=:2222
WARDYN_SSH_ADVERTISE=127.0.0.1:${WARDYN_SSH_PORT:-2222}
# The UI-sandbox relay stays OFF: no agent-vscode or noVNC image is published,
# so the listener would have nothing to serve. See docs/UI-SANDBOXES.md.
# WARDYN_UI_SANDBOX_LISTEN=:8081
# Published images — this install pulls, it never builds.
WARDYN_WARDYND_IMAGE=ghcr.io/${REPO%/*}/wardynd:${SEMVER}
WARDYN_PROXY_IMAGE=ghcr.io/${REPO%/*}/wardyn-proxy:${SEMVER}
WARDYN_AGENT_IMAGES={"claude-code":"ghcr.io/${REPO%/*}/agent-base:${SEMVER}","codex-cli":"ghcr.io/${REPO%/*}/agent-codex-cli:${SEMVER}","aws-sso":"ghcr.io/${REPO%/*}/agent-aws-sso:${SEMVER}"}
EOF
  chmod 600 .env
else
  # UPGRADE PATH. This used to be the whole story — "reusing the existing .env" —
  # and that was a trap. Re-running the installer at a NEW tag overwrites
  # docker-compose.yaml (above) at that tag, while this branch skipped the
  # entire .env write INCLUDING THE IMAGE PINS. The box then ran the new
  # topology against the OLD release's images and was told "Wardyn is running".
  # WARDYN_VERSION did not help: the pins are inside the same guard.
  #
  # Rewrite exactly the version-derived lines and leave everything else — the
  # age key, the admin token, the ports, any hand edits — untouched.
  say "Upgrading the existing ${HOME_DIR}/.env to ${VERSION}"
  env_set() { # KEY VALUE — replace an uncommented KEY= line, or append.
    k=$1; v=$2
    if grep -qE "^${k}=" .env; then
      awk -v k="$k" -v v="$v" 'BEGIN{FS=OFS="="} $1==k {print k "=" v; next} {print}' .env > .env.tmp \
        && mv .env.tmp .env
    else
      printf '%s=%s\n' "$k" "$v" >> .env
    fi
  }
  # The header names a version too; leaving it stale makes the file lie about
  # what it pins.
  awk -v v="${VERSION}" 'NR==1 && /^# Generated by install.sh for Wardyn / {print "# Generated by install.sh for Wardyn " v ". Safe to edit."; next} {print}' .env > .env.tmp && mv .env.tmp .env
  env_set WARDYN_WARDYND_IMAGE "ghcr.io/${REPO%/*}/wardynd:${SEMVER}"
  env_set WARDYN_PROXY_IMAGE "ghcr.io/${REPO%/*}/wardyn-proxy:${SEMVER}"
  env_set WARDYN_AGENT_IMAGES "{\"claude-code\":\"ghcr.io/${REPO%/*}/agent-base:${SEMVER}\",\"codex-cli\":\"ghcr.io/${REPO%/*}/agent-codex-cli:${SEMVER}\",\"aws-sso\":\"ghcr.io/${REPO%/*}/agent-aws-sso:${SEMVER}\"}"
  # Listeners are additive: an install from before they existed has neither, and
  # without them the published ports stay inert.
  grep -qE '^WARDYN_SSH_LISTEN=' .env || printf 'WARDYN_SSH_LISTEN=:2222\n' >> .env
  grep -qE '^WARDYN_SSH_ADVERTISE=' .env || printf 'WARDYN_SSH_ADVERTISE=127.0.0.1:%s\n' "${WARDYN_SSH_PORT:-2222}" >> .env
  chmod 600 .env
fi

say "Pulling signed images"
docker compose pull --quiet 2>/dev/null || docker compose pull

# --no-build is the guarantee: the compose file carries build stanzas for
# contributors, and this install must never trigger one.
say "Starting"
docker compose up -d --no-build

# The CLI. Without it this install has NO host binary at all: the only command
# path is `docker compose exec`, which is in-container and root-only, so
# `wardyn ssh <run-id>` — the whole point of the SSH listener above — has no
# client on the machine that just enabled it. Release assets are per os/arch and
# covered by the cosign-signed SHA256SUMS, so verify before installing.
install_cli() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    *) say "No published wardyn CLI for $(uname -m); skipping (the console still works)"; return 0 ;;
  esac
  case "$os" in linux|darwin) ;; *) say "No published wardyn CLI for ${os}; skipping"; return 0 ;; esac

  asset="wardyn-${os}-${arch}"
  base="https://github.com/${REPO}/releases/download/${VERSION}"
  tmp="${HOME_DIR}/.wardyn-cli.$$"
  curl -fsSL "${base}/${asset}" -o "${tmp}" 2>/dev/null || {
    say "Could not download the ${asset} CLI; skipping (the console still works)"
    rm -f "${tmp}"; return 0
  }

  # Verify against the release's SHA256SUMS. A failure here is FATAL, not a
  # skip: silently installing an unverified binary onto PATH is worse than
  # having no CLI at all.
  if sums=$(curl -fsSL "${base}/SHA256SUMS" 2>/dev/null) && [ -n "${sums}" ]; then
    # SHA256SUMS lists names as `<hash>  ./<name>`, so strip the leading ./ and
    # match the basename EXACTLY — a substring match would let
    # wardyn-linux-amd64 be satisfied by a line for some other asset.
    want=$(printf '%s\n' "${sums}" | awk -v a="${asset}" '{n=$2; sub(/^\.\//,"",n); if (n==a) print $1}' | head -1)
    if [ -n "${want}" ]; then
      if command -v sha256sum >/dev/null 2>&1; then got=$(sha256sum "${tmp}" | awk '{print $1}')
      else got=$(shasum -a 256 "${tmp}" | awk '{print $1}'); fi
      [ "${want}" = "${got}" ] || { rm -f "${tmp}"; die "checksum mismatch for ${asset} (want ${want}, got ${got}) — refusing to install it"; }
    else
      say "SHA256SUMS lists no ${asset}; skipping the CLI rather than installing it unverified"
      rm -f "${tmp}"; return 0
    fi
  else
    say "Could not fetch SHA256SUMS; skipping the CLI rather than installing it unverified"
    rm -f "${tmp}"; return 0
  fi

  chmod 0755 "${tmp}"
  # Prefer a dir already on PATH and writable WITHOUT sudo — this script has not
  # asked for privilege anywhere else and should not start here.
  for d in /usr/local/bin "${HOME}/.local/bin" "${HOME_DIR}/bin"; do
    [ -d "${d}" ] || mkdir -p "${d}" 2>/dev/null || continue
    [ -w "${d}" ] || continue
    mv -f "${tmp}" "${d}/wardyn" 2>/dev/null || continue
    CLI_PATH="${d}/wardyn"
    return 0
  done
  rm -f "${tmp}"
  say "No writable directory on PATH for the CLI; skipping (the console still works)"
}
CLI_PATH=""
say "Installing the wardyn CLI"
install_cli

say "Wardyn is running: http://127.0.0.1:${PORT}"
echo
if [ -n "${CLI_PATH}" ]; then
  echo "  CLI:          ${CLI_PATH}"
  case ":${PATH}:" in
    *":$(dirname "${CLI_PATH}"):"*) ;;
    *) echo "                (not on your PATH — add: export PATH=\"$(dirname "${CLI_PATH}"):\$PATH\")" ;;
  esac
  echo "  Attach:       wardyn ssh <run-id>   (the SSH gateway is on at 127.0.0.1:${WARDYN_SSH_PORT:-2222})"
fi
echo "  Mode:         single-user — you are the admin. Multiple people? https://github.com/${REPO}/blob/${VERSION}/docs/OPERATIONS.md#second-user-same-host"
echo "  Admin token:  grep WARDYN_ADMIN_TOKEN ${HOME_DIR}/.env"
echo "  Stop:         cd ${HOME_DIR} && docker compose down            (keeps all data)"
echo "  Upgrade:      re-run this installer at the new version"
echo "  Uninstall:    cd ${HOME_DIR} && docker compose down            then remove ${HOME_DIR} yourself."
echo "                ${HOME_DIR}/.env holds WARDYN_AGE_KEY in cleartext: deleting it"
echo "                makes every secret stored on this box UNRECOVERABLE. \`docker compose"
echo "                down -v\` additionally destroys every run, recording and audit row."
echo "  Verify what you pulled: https://github.com/${REPO}/blob/${VERSION}/docs/VERIFY.md"
echo
echo "  No model access is configured yet — that is a supported end state."
echo "  Add one in the console under Settings -> Model provider."
