#!/usr/bin/env sh
# Copyright 2025 The Wardyn Authors
# SPDX-License-Identifier: Apache-2.0
#
# install.sh — install Wardyn on this machine.
#
#   curl -fsSL https://github.com/cjohnstoniv/wardyn/releases/download/v0.6.4/install.sh | sh
#
# That URL is the cosign-signed release asset, covered by SHA256SUMS. Curling
# this file from `main` also works, but nothing signs tip-of-main. README.md
# carries the same URL; RELEASING.md step 1b sweeps the version in both.
#
# Pulls the published, cosign-signed images (docs/VERIFY.md) and starts the
# containerized control plane. No clone, no build, no toolchain — Docker is the
# only requirement.
#
# Deploying to Kubernetes instead? That path needs no clone either:
#   helm install wardyn oci://ghcr.io/cjohnstoniv/charts/wardyn --version <ver>
#
# Building from source is a CONTRIBUTOR path, not an install path: see
# CONTRIBUTING.md.
#
# Env: WARDYN_VERSION (default: latest release), WARDYN_HOME (default ~/.wardyn),
#      WARDYN_PORT (default 8080), WARDYN_NS (default "wardyn" — the container-name
#      prefix; change it to run a second install alongside the first).
#
# ponytail: sh, not bash — this is the one script that runs on a machine we know
# nothing about, before anything of ours is installed.
set -eu

REPO=cjohnstoniv/wardyn
HOME_DIR="${WARDYN_HOME:-$HOME/.wardyn}"
PORT="${WARDYN_PORT:-8080}"

say() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is required — https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || die "the docker daemon is not reachable (is Docker running?)"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (docker-compose v1 is not supported)"

# Resolve the version. The GitHub API needs no token for a public repo; if it is
# rate-limited or offline, say so rather than silently installing something else.
#
# NOT `releases/latest`: that endpoint EXCLUDES pre-releases, and RELEASING.md
# mandates `--prerelease` on every Wardyn release — so it returns HTTP 404 and
# this script used to die two lines below on every install. `releases?per_page=1`
# is the newest release of any kind. RELEASING.md says the same thing about
# `releases/latest/download/`.
VERSION="${WARDYN_VERSION:-}"
if [ -z "$VERSION" ]; then
  say "Resolving the latest release"
  VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases?per_page=1" 2>/dev/null \
            | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)
  [ -n "$VERSION" ] || die "could not resolve the latest release — set WARDYN_VERSION=vX.Y.Z"
fi
case "$VERSION" in v*) ;; *) VERSION="v$VERSION" ;; esac
SEMVER="${VERSION#v}"
say "Installing Wardyn ${VERSION} into ${HOME_DIR}"

# Container names are ${WARDYN_NS:-wardyn}-*, so a stack already running from a
# clone owns them. Surface that as a sentence instead of a daemon conflict error
# fifty lines into a compose transcript.
NS="${WARDYN_NS:-wardyn}"
if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "${NS}-api"; then
  die "a Wardyn stack named '${NS}' already exists on this Docker daemon.
  Stop it first (cd ${HOME_DIR} && docker compose down), or install alongside it
  under a different name and free ports:
      WARDYN_NS=wardyn2 WARDYN_PORT=8090 WARDYN_PG_PORT=5433 \\
        WARDYN_REGISTRY_PORT=5011 WARDYN_SSH_PORT=2223 WARDYN_UI_SANDBOX_PORT=8091 \\
        curl -fsSL <this-url> | sh"
fi

mkdir -p "$HOME_DIR"
cd "$HOME_DIR"

# The compose file comes from the tag itself, so this works the moment a release
# exists — no dependency on a release asset having been uploaded.
say "Fetching the compose definition"
curl -fsSL "https://raw.githubusercontent.com/${REPO}/${VERSION}/deploy/compose/docker-compose.yaml" \
  -o docker-compose.yaml || die "could not fetch the compose file for ${VERSION}"

if [ ! -f .env ]; then
  say "Minting this install's secret-store key"
  # Same mechanism the repo's own installers use. The key never leaves this box.
  KEY=$(docker run --rm "ghcr.io/${REPO%/*}/wardynd:${SEMVER}" -gen-age-key 2>/dev/null \
        | grep -E '^AGE-SECRET-KEY-' | head -1 || true)
  [ -n "$KEY" ] || die "could not mint an age key from ghcr.io/${REPO%/*}/wardynd:${SEMVER}"
  TOKEN=$(docker run --rm "ghcr.io/${REPO%/*}/wardynd:${SEMVER}" -gen-age-key 2>/dev/null | sha256sum | cut -c1-48)

  cat > .env <<EOF
# Generated by install.sh for Wardyn ${VERSION}. Safe to edit.
WARDYN_AGE_KEY=${KEY}
WARDYN_ADMIN_TOKEN=${TOKEN}
WARDYN_UP_PORT=${PORT}
WARDYN_NS=${NS}
WARDYN_PG_PORT=${WARDYN_PG_PORT:-5432}
WARDYN_REGISTRY_PORT=${WARDYN_REGISTRY_PORT:-5010}
WARDYN_SSH_PORT=${WARDYN_SSH_PORT:-2222}
WARDYN_UI_SANDBOX_PORT=${WARDYN_UI_SANDBOX_PORT:-8081}
# Published images — this install pulls, it never builds.
WARDYN_WARDYND_IMAGE=ghcr.io/${REPO%/*}/wardynd:${SEMVER}
WARDYN_PROXY_IMAGE=ghcr.io/${REPO%/*}/wardyn-proxy:${SEMVER}
WARDYN_AGENT_IMAGES={"claude-code":"ghcr.io/${REPO%/*}/agent-base:${SEMVER}","codex-cli":"ghcr.io/${REPO%/*}/agent-codex-cli:${SEMVER}","aws-sso":"ghcr.io/${REPO%/*}/agent-aws-sso:${SEMVER}"}
EOF
  chmod 600 .env
else
  say "Reusing the existing ${HOME_DIR}/.env (delete it to start fresh)"
fi

say "Pulling signed images"
docker compose pull --quiet 2>/dev/null || docker compose pull

# --no-build is the guarantee: the compose file carries build stanzas for
# contributors, and this install must never trigger one.
say "Starting"
docker compose up -d --no-build

say "Wardyn is running: http://127.0.0.1:${PORT}"
echo
echo "  Admin token:  grep WARDYN_ADMIN_TOKEN ${HOME_DIR}/.env"
echo "  Stop:         cd ${HOME_DIR} && docker compose down"
echo "  Verify what you pulled: https://github.com/${REPO}/blob/${VERSION}/docs/VERIFY.md"
echo
echo "  No model access is configured yet — that is a supported end state."
echo "  Add one in the console under Settings -> Model provider."
