#!/usr/bin/env bash
# Copyright 2025 The Wardyn Authors
# SPDX-License-Identifier: Apache-2.0
#
# 04-values.sh — render values-entra.yaml (gitignored) from .env.local. This
# is the OIDC overlay applied with --reuse-values on top of the quickstart's
# own install — it does NOT set auth.* (the quickstart's inline admin token
# stays wired as the recovery path; see README.md's Overlay step) and does NOT
# set WARDYN_OIDC_ROLE_MAP's Wardyn.Member row — the eng-group mapping is
# added in the console's People step during the walk, not baked in here, so
# the console write has no chart key to collide with.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/.env.local"
OUT="${ROOT}/values-entra.yaml"

# shellcheck disable=SC1090
[[ -f "${ENV_FILE}" ]] && source "${ENV_FILE}"
for v in TENANT_ID CLIENT_ID HTTP_PORT WARDYN_ADMIN_UPN; do
  [[ -n "${!v:-}" ]] || { echo "${v} not set — run 01-tenant-prep.sh, 02-app.sh and 03-people.sh first" >&2; exit 1; }
done

cat >"${OUT}" <<EOF
# Generated by deploy/azure-entra-sso/04-values.sh from .env.local — gitignored,
# carries no secret itself (the client secret rides in Secret
# wardyn-entra-oidc, referenced below via secretKeyRef, never a literal here).
# Applied with: helm upgrade wardyn deploy/helm/wardyn -n wardyn --reuse-values
#   -f deploy/azure-entra-sso/values-entra.yaml
#   --set-file defaultPolicy=deploy/kind/sso/default-policy.json
env:
  WARDYN_OIDC_ISSUER: "https://login.microsoftonline.com/${TENANT_ID}/v2.0"
  WARDYN_OIDC_CLIENT_ID: "${CLIENT_ID}"
  WARDYN_OIDC_REDIRECT_URL: "http://localhost:${HTTP_PORT}/auth/callback"
  # Wardyn.Admin ONLY. The eng group -> member mapping is added by hand in the
  # console's Getting Started -> People step during the walk (README.md) — a
  # chart entry for it here would collide with that console-managed row on
  # every login (chart entries always win a duplicate key, per docs/ENV.md's
  # WARDYN_OIDC_ROLE_MAP row), silently overriding what the walk demonstrates.
  WARDYN_OIDC_ROLE_MAP: "Wardyn.Admin=admin"
  WARDYN_OIDC_OPERATOR_EMAILS: "${WARDYN_ADMIN_UPN}"
  # Deliberately UNSET:
  #   WARDYN_OIDC_DEFAULT_ROLE   — no match should deny the login, not admit one
  #   WARDYN_OIDC_EMAIL_DOMAINS  — Entra never emits email_verified; setting
  #     this fails EVERY login closed against this tenant (docs/ENV.md, this
  #     README's Context). App Roles + "assignment required" is the tenant
  #     scoping mechanism instead.
extraEnv:
  - name: WARDYN_OIDC_CLIENT_SECRET
    valueFrom:
      secretKeyRef: {name: wardyn-entra-oidc, key: client-secret}
networkPolicy:
  egress:
    extra:
      # The chart's NetworkPolicy is default-deny egress with no rule for an
      # external OIDC issuer (deploy/kind/sso/values.yaml's Dex overlay only
      # needed an in-cluster podSelector rule because Dex runs IN the
      # cluster — login.microsoftonline.com does not). This is the
      # internet-issuer carve-out: TCP/443 to anywhere, since Microsoft's
      # login/graph endpoints are not a stable, allowlistable CIDR.
      - to:
          - ipBlock: {cidr: 0.0.0.0/0}
        ports:
          - protocol: TCP
            port: 443
EOF

chmod 600 "${OUT}"
echo "==> wrote ${OUT}"
