/**
 * Copyright 2025 The Wardyn Authors
 * SPDX-License-Identifier: Apache-2.0
 */

// #1419: SignInSteps now draws through the shared ProgressSteps. The door's
// visible output must not change, so these strings are the markup it rendered
// BEFORE that move (captured from the pre-change component, provider "AWS").
import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import { SignInSteps, type SignInStep } from "./signin-progress";

const BEFORE: Record<SignInStep, string> = {
  "start":
    "<ol class=\"space-y-1.5\" data-testid=\"signin-progress\"><li data-state=\"active\" aria-current=\"step\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-loader-circle lucide-loader-2 size-3.5 shrink-0 animate-spin text-info\" aria-hidden=\"true\"><path d=\"M21 12a9 9 0 1 1-6.219-8.56\"></path></svg>Starting the sign-in sandbox</li><li data-state=\"pending\" class=\"flex items-center gap-2 text-xs text-muted-foreground\"><span class=\"size-3.5 shrink-0 rounded-full border border-border\" aria-hidden=\"true\"></span>Downloading the sign-in image</li><li data-state=\"pending\" class=\"flex items-center gap-2 text-xs text-muted-foreground\"><span class=\"size-3.5 shrink-0 rounded-full border border-border\" aria-hidden=\"true\"></span>Waiting for AWS</li></ol>",
  "download":
    "<ol class=\"space-y-1.5\" data-testid=\"signin-progress\"><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Starting the sign-in sandbox</li><li data-state=\"active\" aria-current=\"step\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-loader-circle lucide-loader-2 size-3.5 shrink-0 animate-spin text-info\" aria-hidden=\"true\"><path d=\"M21 12a9 9 0 1 1-6.219-8.56\"></path></svg>Downloading the sign-in image — first time only</li><li data-state=\"pending\" class=\"flex items-center gap-2 text-xs text-muted-foreground\"><span class=\"size-3.5 shrink-0 rounded-full border border-border\" aria-hidden=\"true\"></span>Waiting for AWS</li></ol>",
  "wait":
    "<ol class=\"space-y-1.5\" data-testid=\"signin-progress\"><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Starting the sign-in sandbox</li><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Downloading the sign-in image</li><li data-state=\"active\" aria-current=\"step\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-loader-circle lucide-loader-2 size-3.5 shrink-0 animate-spin text-info\" aria-hidden=\"true\"><path d=\"M21 12a9 9 0 1 1-6.219-8.56\"></path></svg>Waiting for AWS</li></ol>",
  "ready":
    "<ol class=\"space-y-1.5\" data-testid=\"signin-progress\"><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Starting the sign-in sandbox</li><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Downloading the sign-in image</li><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Waiting for AWS</li></ol>",
  "download-failed":
    "<ol class=\"space-y-1.5\" data-testid=\"signin-progress\"><li data-state=\"done\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-check size-3.5 shrink-0 text-success\" aria-hidden=\"true\"><path d=\"M20 6 9 17l-5-5\"></path></svg>Starting the sign-in sandbox</li><li data-state=\"failed\" class=\"flex items-center gap-2 text-xs text-foreground\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-triangle-alert lucide-alert-triangle size-3.5 shrink-0 text-danger\" aria-hidden=\"true\"><path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\"></path><path d=\"M12 9v4\"></path><path d=\"M12 17h.01\"></path></svg>Downloading the sign-in image — failed</li></ol>",
};

describe("SignInSteps markup is unchanged by the shared step list", () => {
  it.each(Object.keys(BEFORE) as SignInStep[])("step %s", (step) => {
    const { container } = render(<SignInSteps step={step} provider="AWS" />);
    expect(container.innerHTML).toBe(BEFORE[step]);
  });
});
